Models/RentBooks.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace OnlineLibrary.Models
{
    public class RentBooks
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string? _id { get; set; }
        [BsonRepresentation(BsonType.ObjectId)]
        public string? BooksId { get; set; }
        public string NISPeminjam { get; set; }
        public string JudulBuku { get; set; }
        public DateTime TanggalPeminjaman { get; set; } = DateTime.Now;
        public DateTime TenggatPengembalian { get; set; } = DateTime.Now.AddDays(7);
        public Pengembalian Pengembalian { get; set; } = new Pengembalian();


        public RentBooks(string Book, string NIS, string Judul)
        {
            NISPeminjam = NIS;
            BooksId = Book;
            JudulBuku = Judul;
        }

    }

    public class Pengembalian
    {
        public Boolean StatusPengembalian { get; set; } = false;
        public DateTime? TanggalPengembalian { get; set; } = null;
        public int NominalDenda { get; set; } = 0;
    }
}

Controllers/RentBooksController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnlineLibrary.Interfaces;
using OnlineLibrary.Models;
using System.Dynamic;

namespace OnlineLibrary.Controllers
{
    public class RentBooksController : Controller
    {
        private readonly IBooks _books;
        private readonly IUsers _users;
        private readonly IRentBooks _rentbooks;

        public RentBooksController(IBooks book, IRentBooks rentbook, IUsers user)
        {
            _books = book;
            _users = user; 
            _rentbooks = rentbook;
        }

        public IActionResult Index()
        {
            if(HttpContext.Session.GetString("Role") == "Admin")
            {
                return View(_rentbooks.GetAllRentBooks());
            }
            else
            {
                return RedirectToAction("Index", " Home");
            }
        }
        [HttpGet]
        public IActionResult pinjambuku(string bookId)
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.Books = _books.GetBookDetails(bookId);
            RentBooks newrent = new RentBooks(bookId, HttpContext.Session.GetString("NIS"), mymodel.Books.Judul);
            mymodel.RentBooks = newrent;
            return View(mymodel);
        }
        [HttpPost]
        public IActionResult pinjambukuPost(string NIS, string bookId)
        {
            var judul = _books.GetBookDetails(bookId).Judul;
            RentBooks rent = new RentBooks(bookId, NIS, judul);
            _rentbooks.pinjam(rent, NIS, bookId);
            return RedirectToAction("Index", "Books");
        }

        [HttpGet]
        public IActionResult kembalikanbuku(string rentid)
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.RentBooks = _rentbooks.GetRentBookDetails(rentid);
            mymodel.Books = _books.GetBookDetails(mymodel.RentBooks.BooksId);

            return View(mymodel);
        }

        [HttpPost]
        public IActionResult kembalikanbukuPost(string rentid, string NIS)
        {
            _rentbooks.kembali(rentid);
            return RedirectToAction("Index", "Users", new { NIS = NIS});
        }
        [HttpGet]
        public IActionResult daftarPeminjaman(string userId)
        {
            var x = _rentbooks.GetUserRentBooks(userId);
            return View(x);
        }

    }
}

Views/RentBooks/Index.cshtml
@model IEnumerable<OnlineLibrary.Models.RentBooks>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model._id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BooksId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NISPeminjam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JudulBuku)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TanggalPeminjaman)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenggatPengembalian)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item._id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BooksId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NISPeminjam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JudulBuku)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TanggalPeminjaman)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenggatPengembalian)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Views/RentBooks/daftarPeminjaman.cshtml
@model IEnumerable<OnlineLibrary.Models.RentBooks>

@{
    ViewData["Title"] = "daftarPeminjaman";
}

<h2>daftarPeminjaman</h2>
<table class="table table-bordered border-white table-info table-striped text-center">
    <thead class="table-dark  border-white">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JudulBuku)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TanggalPeminjaman)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenggatPengembalian)
            </th>
            <th>
                kembalikan
            </th>
            <th>
                Denda
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="align-middle">
            <td  >
                @Html.DisplayFor(modelItem => item.JudulBuku)
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.TanggalPeminjaman)
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.TenggatPengembalian)
            </td>
            <td >
                @if (!item.Pengembalian.StatusPengembalian)
                {
                    @Html.ActionLink("Kembalikan", "kembalikanbuku", "RentBooks", new { rentid = item._id }, new { @class="btn btn-outline-success m-auto"})
                }else {
                     @Html.ActionLink("Kembalikan", "kembalikanbuku", "RentBooks", null, new { @class="btn btn-secondary disabled text-center"})
                }
            </td>
            <td>
                @if (item.Pengembalian.StatusPengembalian)
                {
                    @Html.DisplayFor(modelItem => item.Pengembalian.NominalDenda)
                }else {
                    @:None 
                }
            </td>
        </tr>
}
    </tbody>
</table>

Views/RentBooks/kembalikanbuku.cshtml
@model dynamic;
@using OnlineLibrary.Models;

@{
    ViewData["Title"] = "pinjambuku";
}

<h2>Peminjaman Buku</h2>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-3">
            Judul:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.Judul
        </dd>
        <dt class = "col-sm-3">
            Tanggal Terbit:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.TanggalTerbit
        </dd>
        <dt class = "col-sm-3">
            Kategori:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.Kategori
        </dd>
        <dt class = "col-sm-3">
            Penulis:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.Penulis
        </dd>
        <dt class = "col-sm-3">
            Penerbit:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.Penerbit
        </dd>
        <dt class = "col-sm-3">
            Status Ketersediaan:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.StatusKetersediaan
        </dd>
        <dt class = "col-sm-3">
            Tanggal Peminjaman: 
        </dt>
        <dd class = "col-sm-9">
            @Model.RentBooks.TanggalPeminjaman.ToString("dd-MM-yyyy")
        </dd>
        <dt class = "col-sm-3">
            Tenggat Pengembalian: 
        </dt>
        <dd class = "col-sm-9">
            @Model.RentBooks.TenggatPengembalian.ToString("dd-MM-yyyy")
        </dd>
        <dt class = "col-sm-3">
            Tanggal Hari Ini: 
        </dt>
        <dd class = "col-sm-9">
            @{var x = (int)(DateTime.Now - Model.RentBooks.TenggatPengembalian).TotalDays ;}
            @if((int)(DateTime.Now - Model.RentBooks.TenggatPengembalian).TotalDays > 0)
            {
                @:<p class="text-danger"> @DateTime.Now.ToString("dd-MM-yyyy") </p>
            }else
            {
                @:<p class="text-success"> @DateTime.Now.ToString("dd-MM-yyyy") </p>
            }
        </dd>
    </dl>
</div>
<div>
    <form  asp-action="kembalikanbukuPost" asp-controller="RentBooks">
         <input type="hidden" name="rentid" value="@Model.RentBooks._id" class="form-control"/>
         <input type="hidden" name="NIS" value="@Model.RentBooks.NISPeminjam" class="form-control"/>
         <input type="submit" value="Kembalikan Buku" class="btn btn-success me-2" />
         @Html.ActionLink("Batal", "Index", "Books", null, new { @class="btn btn-danger mx-2" })
    </form>
</div>

Views/RentBooks/pinjambuku.cshtml
@model dynamic;
@using OnlineLibrary.Models;

@{
    ViewData["Title"] = "pinjambuku";
}

<h2>Peminjaman Buku</h2>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-3">
            Judul:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.Judul
        </dd>
        <dt class = "col-sm-3">
            Tanggal Terbit:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.TanggalTerbit
        </dd>
        <dt class = "col-sm-3">
            Kategori:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.Kategori
        </dd>
        <dt class = "col-sm-3">
            Penulis:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.Penulis
        </dd>
        <dt class = "col-sm-3">
            Penerbit:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.Penerbit
        </dd>
        <dt class = "col-sm-3">
            Status Ketersediaan:
        </dt>
        <dd class = "col-sm-9">
            @Model.Books.StatusKetersediaan
        </dd>
        <dt class = "col-sm-3">
            Tanggal Peminjaman: 
        </dt>
        <dd class = "col-sm-9">
            @Model.RentBooks.TanggalPeminjaman
        </dd>
        <dt class = "col-sm-3">
            Tenggat Pengembalian: 
        </dt>
        <dd class = "col-sm-9">
            @Model.RentBooks.TenggatPengembalian
        </dd>
    </dl>
</div

<div class="row">
    <form  asp-action="pinjambukuPost" asp-controller="RentBooks">
         <input type="hidden" name="NIS" value="@Model.RentBooks.NISPeminjam" class="form-control"/>
         <input type="hidden" name="bookId" value="@Model.Books._id" class="form-control"/>
         <input type="submit" value="pinjambukuPost" class="btn btn-success me-2" />
         @Html.ActionLink("Batal", "Index", "Books", null, new { @class="btn btn-danger mx-2" })
    </form>
@*    @Html.ActionLink("Konfirmasi Peminjaman", "pinjambukuPost", "RentBooks", new { NIS = Model.RentBooks.NISPeminjam, bookId = Model.Books._id  }, new { @class="btn btn-success me-2" })*@
</div>